### PR TITLE
Remove dashes in README

### PR DESCRIPTION
**Pull request by platy11**

### CODE REVIEW

**Comment by Toby56** [comment]
LGTM!

**Comment by platy11** [comment]
LGTM - @tradeandmark/all Should we merge?

**Comment by Toby56** [comment]
Yes

**Comment by Toby56** [comment]
LGTM! LGTM! LGTM! LGTM! LGTM! LGTM! LGTM! LGTM! LGTM! LGTM! LGTM! LGTM! LGTM!

**Pull request merged**
